name: "Release:Storybook"

on:
  push:
    branches:
      - master

jobs:
  release:
    name: "storybook"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: NPM install
        uses: bahmutov/npm-install@v1

      - name: Build Application
        run: npm run deploy:storybook

      - name: Deploy production to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_STORYBOOK_SITE }}
          build-dir: "./packages/client/storbook"
          comment-on-commit: true
          draft: false
